const employees = [
    {
        "id": 1,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 2,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 3,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 4,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 5,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 6,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 7,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 8,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 9,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 10,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 11,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
    {
        "id": 12,
        "First Name": "firstName",
        "Last Name": "lastName",
        "Start Date": "startDate",
        "Department": "department" ,
        "Date of Birth": "dateOfBirth",
        "Street": "street",
        "City": "city",
        "State": "state",
        "Zip Code": "zipCode",
    },
]