const employees = [
    {
        "id": 1,
        "First Name": "Benito",
        "Last Name": "Casan",
        "Start Date": "01/08/1842",
        "Department": "Marketing" ,
        "Date of Birth": "03/05/1828",
        "Street": "14 rue Victor Hugo",
        "City": "Sète",
        "State": "Virginia",
        "Zip Code": "001",
    },
    {
        "id": 2,
        "First Name": "Rosa",
        "Last Name": "Salvado",
        "Start Date": "07/11/1953",
        "Department": "Sales" ,
        "Date of Birth": "08/01/1924",
        "Street": "2 rue Gambetta",
        "City": "Pezenas",
        "State": "South Carolina",
        "Zip Code": "002",
    },
    {
        "id": 3,
        "First Name": "Adan",
        "Last Name": "Cerda",
        "Start Date": "09/12/1920",
        "Department": "Human Ressources" ,
        "Date of Birth": "01/08/1900",
        "Street": "Le travers",
        "City": "Saint-Malo",
        "State": "South Dakota",
        "Zip Code": "003",
    },
    {
        "id": 4,
        "First Name": "Anton",
        "Last Name": "Robershow",
        "Start Date": "20/01/1953",
        "Department": "Legal" ,
        "Date of Birth": "12/06/1924",
        "Street": "16 bd Las Vegas",
        "City": "USA",
        "State": "California",
        "Zip Code": "004",
    },
    {
        "id": 5,
        "First Name": "Fabiano",
        "Last Name": "Reno",
        "Start Date": "04/09/1884",
        "Department": "Engineering" ,
        "Date of Birth": "21/02/1860",
        "Street": "21 dock of marina",
        "City": "Arkansas",
        "State": "Tennessee",
        "Zip Code": "005",
    },
    {
        "id": 6,
        "First Name": "Bob",
        "Last Name": "Kennedy",
        "Start Date": "24/07/1946",
        "Department": "Sales" ,
        "Date of Birth": "22/05/1923",
        "Street": "678 North Playa",
        "City": "Manathan",
        "State": "Florida",
        "Zip Code": "006",
    },
    {
        "id": 7,
        "First Name": "Harry",
        "Last Name": "Potter",
        "Start Date": "31/10/1986",
        "Department": "Engineering" ,
        "Date of Birth": "03/03/1960",
        "Street": "Palais de Windsor",
        "City": "Windsor",
        "State": "Alabama",
        "Zip Code": "007",
    },
    {
        "id": 8,
        "First Name": "Gulum",
        "Last Name": "monster",
        "Start Date": "04/08/1977",
        "Department": "Sales" ,
        "Date of Birth": "29/01/1952",
        "Street": "valls de Andorra",
        "City": "Puicerda",
        "State": "Mississippi",
        "Zip Code": "008",
    },
    {
        "id": 9,
        "First Name": "Pedro",
        "Last Name": "Antonio",
        "Start Date": "1998",
        "Department": "Legal" ,
        "Date of Birth": "16/09/1978",
        "Street": "10 de la Vega",
        "City": "Las Vegas",
        "State": "Virginia",
        "Zip Code": "009",
    },
    {
        "id": 10,
        "First Name": "Juan",
        "Last Name": "Salvado",
        "Start Date": "01/12/2014",
        "Department": "Human Ressources" ,
        "Date of Birth": "28/02/1994",
        "Street": "118 Time Square",
        "City": "Liverpool",
        "State": "New Jersey",
        "Zip Code": "010",
    },
    {
        "id": 11,
        "First Name": "Tonio",
        "Last Name": "FERREIRA",
        "Start Date": "31/01/2022",
        "Department": "Marheting" ,
        "Date of Birth": "12/08/2002",
        "Street": "2 av de la playa",
        "City": "Lille",
        "State": "south Carolina",
        "Zip Code": "011",
    },
    {
        "id": 12,
        "First Name": "Maria",
        "Last Name": "Miguel",
        "Start Date": "18/12/2023",
        "Department": "Engineering" ,
        "Date of Birth": "25/09/2001",
        "Street": "Ile de Saint Denis",
        "City": "Saint-Denis",
        "State": "florida",
        "Zip Code": "012",
    },
]
export default employees;
